# Site
name: "sheikirfanbasha"
description: "Irfan's blog"
meta_description: "sheikirfanbasha blog, Machine Learning, Augmented Reality, Artificial Intelligence"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-60325064-4'
disqus: 'sheikirfanbasha'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  sheikirfanbasha:
    name: sheikirfanbasha
    display_name: Irfan
    gravatar: 13dc56ac552dcaff219097821c994455
    email: sheikirfanbasha@gmail.com
    web: https://www.linkedin.com/in/sheikirfanbasha
    twitter: https://twitter.com/sheikirfanbasha
    description: "I am Computer Science Engineer, passionate in developing applications related to Augmented Reality and Machine Learning."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge